server:
  port: 8085


spring:
  application:
    name: msa-wr-weather-data-server
  redis:
    port: 6379
    host: localhost
    database: 0
    password:
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1ms

eureka:
  client:
    service-url.defaultZone: http://localhost:8761/eureka/